### ISSUE TITLE
职责链 中 有一个小错误

### ISSUE THREAD

**Issue by WeiYYin** [Yvette2333/design-pattern#1]
![1590655560534](https://user-images.githubusercontent.com/33323771/83119801-bceee200-a102-11ea-9cb6-be8d78194c42.jpg)

chainOrder500.setNextSuccessor( chainOrder200 )
chainOrder200.setNextSuccessor( chainOrderNormal )

**Comment by Yvette2333** [comment]
谢谢，已更改
![image](https://user-images.githubusercontent.com/61384119/83232606-081afa80-a1c0-11ea-9726-a3d2fc09152a.png)
